### ISSUE TITLE
Update Progressbar after data changed

### ISSUE THREAD

**Issue by MiladFaridnia** [antoninbiret/ABSteppedProgressBar#18]
How can I inform progressbar that my data has updated ? I need a method like reloadData() in tableviews.

**Comment by antoninbiret** [comment]
Hi @MiladFaridnia. Unfortunately the progress bar doesn't have any method like a `reloadData()`. This method could be easily added. Actually to redraw the progress bar, you need to call the private func `_setNeedsRedraw()` (PR is welcome). As a workaround, you can set the same `numberOfPoints` as before in order to redraw the view. Hope it helps (if it was not too late).
